  GNU nano 6.2                        main.yml
  # This workflow contains a single job called "build"
  demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the >
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acc>
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Test add script
        run: |
          sudo chmod +x add.sh test-add.sh
          ./test-add.sh
  GNU nano 6.2                        main.yml
  # This workflow contains a single job called "build"
  demo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the >
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can acc>
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      # - name: Run a one-line script
      #   run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Test add script
        run: |
          sudo chmod +x sub.sh test-sub.sh
          ./test-sub.sh


